services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: sukientot
        restart: unless-stopped
        ports:
            - '10011:80'
        volumes:
            # Mount storage directory (persistent uploads & logs)
            - ./storage:/var/www/html/storage

            # Mount environment file
            - ./.env:/var/www/html/.env
        networks:
            - web-network

networks:
    web-network:
        external: true
