services:
    app:
        build:
            context: .
            dockerfile: dockerfile
        container_name: sukientot
        restart: unless-stopped
        ports:
            - '10010:80'
        volumes:
            # Mount source code (excluding vendor)
            - ./app:/var/www/html/app
            - ./config:/var/www/html/config
            - ./database:/var/www/html/database
            - ./lang:/var/www/html/lang
            - ./resources:/var/www/html/resources
            - ./routes:/var/www/html/routes
            - ./tests:/var/www/html/tests

            # Mount public directory
            - ./public:/var/www/html/public

            # Mount storage directory
            - ./storage:/var/www/html/storage

            # Mount environment files
            - ./.env:/var/www/html/.env

            # Mount configuration files
            - ./artisan:/var/www/html/artisan
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - ./package.json:/var/www/html/package.json
            - ./package-lock.json:/var/www/html/package-lock.json
            - ./vite.config.ts:/var/www/html/vite.config.ts
            - ./tsconfig.json:/var/www/html/tsconfig.json
            - ./tailwind.config.js:/var/www/html/tailwind.config.js
            - ./postcss.config.js:/var/www/html/postcss.config.js
            - ./phpunit.xml:/var/www/html/phpunit.xml

            # Mount bootstrap directory
            - ./bootstrap:/var/www/html/bootstrap
        networks:
            - web-network

networks:
    web-network:
        external: true
